name: Build Mikage on x86 Mac

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:  # Allow manual triggering

jobs:
  build:
    runs-on: macos-latest  # 使用GitHub提供的macOS最新版本运行器
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install build dependencies
      run: |
        brew update
        brew install conan cmake ninja pkg-config
      # 根据Mikage的实际需求，你可能需要在此添加其他依赖库

    - name: Configure with Conan
      run: |
        mkdir build
        cd build
        conan install .. -of . --build=missing
      # 如需Debug构建，将上行改为：
      # conan install .. -of . --build=missing -s build_type=Debug

    - name: Configure with CMake
      run: |
        cd build
        cmake .. -G Ninja --toolchain conan_toolchain.cmake -DCMAKE_BUILD_TYPE=Release
      # 如需Debug构建，将上行改为：
      # cmake .. -G Ninja --toolchain conan_toolchain.cmake -DCMAKE_BUILD_TYPE=Debug

    - name: Build and install
      run: |
        cd build
        ninja && sudo ninja install
