name: Build Mikage on x86 Mac

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install build dependencies
      run: |
        brew update
        brew install conan cmake ninja pkg-config

    - name: Configure Conan default profile
      run: conan profile detect --force

    - name: Configure with Conan
      run: |
        mkdir build
        cd build
        conan install .. -of . --build=missing

    - name: Configure with CMake
      run: |
        cd build
        cmake .. -G Ninja --toolchain conan_toolchain.cmake -DCMAKE_BUILD_TYPE=Release

    - name: Build and install
      run: |
        cd build
        ninja && sudo ninja install
