name: Windows Build

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Conan
      run: |
        python -m pip install --upgrade pip
        pip install conan

    - name: Detect and create default Conan profile
      run: conan profile detect --force

    - name: Modify Conan profile for C++17
      run: |
        # 获取profile文件路径
        $profilePath = "$env:USERPROFILE\.conan2\profiles\default"
        
        # 读取文件内容
        $content = Get-Content $profilePath -Raw
        
        # 检查是否已包含cppstd设置
        if ($content -match 'compiler\.cppstd') {
            # 替换现有的cppstd设置
            $content = $content -replace 'compiler\.cppstd\s*=\s*\w+', 'compiler.cppstd=17'
        } else {
            # 在[settings]部分添加cppstd设置
            $content = $content -replace '(\[settings\])', "`$1`ncompiler.cppstd=17"
        }
        
        # 确保arch设置正确
        if ($content -match 'arch\s*=') {
            $content = $content -replace 'arch\s*=\s*\w+', 'arch=x86_64'
        } else {
            $content = $content -replace '(\[settings\])', "`$1`narch=x86_64"
        }
        
        # 写回文件
        Set-Content -Path $profilePath -Value $content
        
        # 显示修改后的profile内容
        Write-Host "Modified Conan profile:"
        Get-Content $profilePath
      shell: pwsh

    - name: Verify Conan profile
      run: conan profile show

    - name: Setup Visual Studio environment
      uses: ilammy/msvc-dev-cmd@v1

    - name: Install Ninja
      run: |
        choco install ninja -y

    - name: Create build directory
      run: mkdir build

    - name: Configure Conan and install dependencies
      working-directory: ./build
      run: |
        conan install .. -of . --build=missing

    - name: Configure CMake (alternative approach)
      working-directory: ./build
      run: |
        # 方法1: 尝试不使用工具链文件
        # cmake .. -G Ninja -DCMAKE_BUILD_TYPE=$env:BUILD_TYPE -DCMAKE_CXX_STANDARD=17
        
        # 如果上面失败，可以尝试方法2: 使用Visual Studio生成器而不是Ninja
        cmake .. -G "Visual Studio 17 2022" -A x64 -DCMAKE_BUILD_TYPE=$env:BUILD_TYPE

    - name: Build with Ninja
      working-directory: ./build
      run: |
        ninja

    - name: Install
      working-directory: ./build
      run: |
        ninja install

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: mikage-windows-build
        path: |
          build/
          !build/CMakeFiles/
        retention-days: 7
